### ISSUE TITLE
Migrate transport.transaction.stress.js from functional/ws suite to integration

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1004]
Currently this test is failing in the nightly builds. I've checked the test locally and it fails too. Line related:
https://github.com/LiskHQ/lisk/blob/ce63cb6751aee62e0bcfa8fdd12fe876cf725ea9/test/functional/ws/transport.transactions.stress.js#L53

As discussed, we should move this test from `functional/ws` to the refactored `integration` suite which will be perform in a separated issue.

**Comment by MaciejBaj** [comment]
`transport.transaction.stress.js` functional tests are reusing logic contained in `test/node.js` module, which cannot be reused in integration tests. It performs API calls just after requiring the file against running Lisk instance on HTTP port 5000. The condition is not fulfilled in integration tests though. 
In order to proceed with the rewrite parts of logic responsible for: 
- [ ] generating transactions using `lisk-js`
- [ ] reusing constants directly from `helpers/constants.js`
- [ ] waiting for resources
- [ ] generating random data
- [ ] reusing data of devnet genesis accounts
needs to be extracted as separate modules, independent from `test/node.js`.
