### ISSUE TITLE
Bug on migrations from 0.9.9 to 1.0.0 schema

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1070]
Migrations which updates a database containing  a v0.9.9 schema to v1.0 fail on the next point:  
```
[ERR] 2017-12-05 10:27:24 | BatchError: ERROR:  function validatemembalances() does not exist
LINE 1: SELECT * FROM validateMemBalances()
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

    at check (/Users/diego-g/git/lisk/node_modules/spex/lib/ext/batch.js:133:32)
    at step (/Users/diego-g/git/lisk/node_modules/spex/lib/ext/batch.js:107:17)
    at /Users/diego-g/git/lisk/node_modules/spex/lib/ext/batch.js:82:17
    at /Users/diego-g/git/lisk/node_modules/spex/lib/utils/index.js:62:25
```

**Comment by 4miners** [comment]
Of course it will fail, it's how our migrations works.

0.9.11 migrations: https://github.com/LiskHQ/lisk/tree/0.9.11/sql/migrations
last few:
- **20170428001337_recreateTrsLiskView.sql** _(first common)_
- 20170614155841_uniqueDelegatesConstraint.sql _(not yet backported to 1.0.0?)_
- **20170921105500_recreateRevertMemAccountTrigger.sql** _(last common)_

1.0.0 migrations: https://github.com/LiskHQ/lisk/tree/1.0.0/sql/migrations
last few:
- **20170428001337_recreateTrsLiskView.sql** _(first common)_
- 20170704152203_removePeersDappTable.sql
- 20170807001337_roundsRewards.sql
- 20170807101337_validateMemTables.sql
- 20170807201337_generateDelegatesList.sql
- 20170807301337_roundsRewrite.sql
- 20170814143733_createTransferTrsTable.sql
- 20170814144034_recreateFullBlockListView.sql
- **20170921105500_recreateRevertMemAccountTrigger.sql** _(last common)_

When apply 1.0.0 on top of 0.9.11 branch - last migration that is present on both branches is **20170921105500_recreateRevertMemAccountTrigger.sql** - and because of that other migrations will not be executed.

We need consistency, so if we backport migration that is already live - all other migrations that are not live yet should be renamed to be executed after last backported migration.
