### ISSUE TITLE
 Node app.js does not do anything, http://localhost:8000  or 7000 unable to connect

### ISSUE THREAD

**Issue by xiubinzheng** [LiskHQ/lisk#1083]
Hi, 

I am following the system install instruction here and got all the way to the step of 
managing Lisk, 

**I ran the node app.js command, and it just terminates immediately. both
http://localhost:8000  or 7000 are unable to connect.** 

when I run the node app.js it just terminates immediate without showing me any logs to debugs with. What could be the issue?

**Comment by MichalTuleja** [comment]
Hello @xiubinzheng ,
which branch are you using?

**Comment by sdrpa** [comment]
Provided that you've compiled the code successfully, following steps from

1. https://docs.lisk.io/docs/core-pre-installation-source
2. https://docs.lisk.io/docs/core-installation-source-test

Do ```pm2 start app.js``` then check the logs:

1.  /home/[username]/.pm2/logs/app-error-0.log
2. home/[username]/.pm2/logs/app-out-0.log

Some things I found in the last 2 days:

1. Sometimes ```pm2 show app``` reports 'online' status after you start the app, but ```netstat -tulnp``` says no process is listening on port 7000. Check the logs...
2. You have to import db in order to successfully start app:

```
pm2 stop app.js
dropdb lisk_test
wget https://downloads.lisk.io/lisk/test/blockchain.db.gz
createdb lisk_test
gunzip -fcq blockchain.db.gz | psql -d lisk_test
pm2 start app.js
```

I can't tell you how to create a genesis block from scratch, I'm testing it out, there is a sample script (which probably needs adjusting) I found at Ark project (fork of Lisk) - https://github.com/ArkEcosystem/ark-node/blob/development/tasks/createGenesisBlock.js but I haven't tested it in detail.

**Comment by karmacoma** [comment]
Thanks for lending a hand @sdrpa 👍
