### ISSUE TITLE
Partition API over two ports (one of peers, other for client)

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#11]
There is, I think, a potential weakness in the lisk client.
All interaction with the client goes over port 7000. The communication is not encrypted, so the whole internet can track it.
For the peering API this is necessary and ok, but not for the other node and dapp APIs.
For example, the transmission of the passphrase (secret) should always be encrypted (e.g. /api/accounts/open). That should be also true for the GUI (I don't know, if secrets are directly transmitted).
For all this the SSL access is available and should be forced to use.
Suggestion:
* Divide the necessarily exposed (open) API (e.g. /api/peers) from all other APIs -> two different ports
* The node operator can decide to bind the second port to localhost or to all (0.0.0.0)

I config.json I found the two options "serveHttpAPI" and "serveHttpWallet". Perhaps they were intended for a similar purpose, but I found no usage in the lisk/crypti sources.

**Comment by fix** [comment]
Closing as duplicate of #39 #10

- The main idea is to rework the GUI using lisk-js so there is no need to send passphrase over the network anymore, since all transactions can be signed locally.
- In the meantime people should exclusively use nodes that have enabled https.
- yes serveHttpAPI and serveHttpWallet are not used, however it could be wise to set whitelist for api and wallet. it would act the same as for security.
