### ISSUE TITLE
Delegates API endpoint responds with error for valid usernames

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1101]
The only requirement on delegate usernames specified [in the docs](https://docs.lisk.io/docs/the-lisk-protocol-transactions) is that the length should be between 1 and 20 characters. So `123` should be a valid delegate username.

However, querying by usernames which consist only of numerical characters responds with an error:
```sh
$ curl --silent node07.lisk.io:8000/api/delegates/get?username=123abc | jq
{
  "success": false,
  "error": "Delegate not found"
}
$ curl --silent node07.lisk.io:8000/api/delegates/get?username=123 | jq
{
  "success": false,
  "error": "Expected type string but found type integer"
}
```

**Comment by nazarhussain** [comment]
@karmacoma The problem is that we express framework is considering `123` as integer value, while we have a restriction of a string value. Delegates registered successfully as it was initially sent in a JSON body with quoted `"123"` value. 

So we need to update delegate registration logic to make sure delegate name must have at least one character. Current logic for username is `^[a-z0-9!@$&_.]+$`, so all these are valid usernames. 

- abdfd3343
- abcd@nazar
- abcd!nazar
- abd&nazar
- abd_nazar

I believe we should revise what special characters in username to be allowed?

**Comment by nazarhussain** [comment]
@karmacoma We need to verify if we don't have any existing delegate with pure integer usernames, then we can make this change to ensure we have at least one alpha numeric character in delegate user name.

**Comment by nazarhussain** [comment]
@karmacoma If we want to allow username as only integer characters, we can achieve it by modifying this code block.

https://github.com/LiskHQ/lisk/blob/62e26dfa8c6b153b4e628042492426e7512afee5/app.js#L332-L347

**Comment by nazarhussain** [comment]
Just checked main net database and found few purely integer usernames. So we have to refactor above code to allow integer usernames in query.
