### ISSUE TITLE
api/transactions/unconfirmed is limited to 25tx

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#1150]
Endpoint `api/transactions/unconfirmed`
Is limited to 25 transactions while it should either display all unconfirmed tx or with some sort of paging. Per docs there are no arguments in this endpoint.
0.9.10

**Comment by karmacoma** [comment]
Hi @karek314 

Thanks for opening this issue, much appreciated.

Currently, each node applies a maximum of 25 transactions in `unconfirmed` states. With remaining transactions sitting it on `api/transactions/queued`, verified but not yet applied.

This limitation was imposed due to the performance penalty that came from applying/undoing transactions in `unconfirmed` states, especially during sync. For `0.9.*` this behavior will remain, but in `1.0.0` the transaction pool has been rewritten to handle unconfirmed state in memory, rather than writing it constantly to the db.

We have also improved the API for querying the pool, details of which can be found here:

https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.20#/Queue/getPooledTransactions

**Comment by karek314** [comment]
@karmacoma Nice, looking forward for 1.0.0. Thank you +1
