### ISSUE TITLE
Fix failing tests in test/unit/modules/blocks/verify.js

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1227]
Parent: #1176 

Affects: `1.0.0`

**Comment by diego-G** [comment]
The entire block of tests is being skipped.

**Comment by karmacoma** [comment]
Errors currently being thrown when enabled:

```
9 failing

  1) blocks/verify
       processBlock() for valid block {broadcast: true, saveBlock: true}
         should be ok when processing block 1:
     Error: done() invoked with non-Error: Failed to verify slot: 3257837
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:636:13)
  

  2) blocks/verify
       processBlock() for invalid block {broadcast: true, saveBlock: true}
         should fail when processing block 1 again (checkExists):

      Uncaught AssertionError: expected 'Failed to verify slot: 3257837' to equal 'Block 7228164774750412618 already exists'
      + expected - actual

      -Failed to verify slot: 3257837
      +Block 7228164774750412618 already exists
      
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:658:20)
  

  3) blocks/verify
       processBlock() for invalid block {broadcast: false, saveBlock: true}
         should fail when transaction is already confirmed (fork:2):

      Uncaught AssertionError: expected 'Failed to verify slot: 3377286' to equal 'Transaction is already confirmed: 7249285091378090017'
      + expected - actual

      -Failed to verify slot: 3377286
      +Transaction is already confirmed: 7249285091378090017
      
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:772:21)
  

  4) blocks/verify
       processBlock() for valid block {broadcast: false, saveBlock: true}
         should be ok when processing block 2:
     Error: done() invoked with non-Error: Failed to verify slot: 3377286
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:802:13)
  

  5) blocks/verify
       processBlock() for valid block {broadcast: false, saveBlock: true}
         should fail when processing block 2 again (checkExists):

      Uncaught AssertionError: expected 'Failed to verify slot: 3377286' to equal 'Block 1905024026221938223 already exists'
      + expected - actual

      -Failed to verify slot: 3377286
      +Block 1905024026221938223 already exists
      
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:817:20)
  

  6) blocks/verify
       processBlock() for valid block {broadcast: true, saveBlock: false}
         should be ok when broadcasting block 3:
     Error: done() invoked with non-Error: Failed to verify slot: 3394263
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:847:13)
  

  7) blocks/verify
       processBlock() for valid block {broadcast: true, saveBlock: false}
         should be ok when broadcasting block 3 again (checkExists):
     Error: done() invoked with non-Error: Failed to verify slot: 3394263
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:871:13)
  

  8) blocks/verify
       processBlock() for valid block {broadcast: false, saveBlock: false}
         should be ok when receiving block 3:
     Error: done() invoked with non-Error: Failed to verify slot: 3394263
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:900:13)
  

  9) blocks/verify
       processBlock() for valid block {broadcast: false, saveBlock: false}
         should be ok when receiving block 3 again (checkExists):
     Uncaught AssertionError: expected [ Array(12) ] to not include 'broadcastBlock'
    at Immediate.<anonymous> (test/unit/modules/blocks/verify.js:917:55)
```

**Comment by 4miners** [comment]
We get `Failed to verify slot: 3257837` because the tests have been implemented incorrectly.

For example - first test `should be ok when processing block 1`:
- we overwrite last block with some block that have height `489`
- then we create another block and try to process it, we hit:
https://github.com/LiskHQ/lisk/blob/175cdc9755d06459a9f734acd9addfb27fe5147d/modules/delegates.js#L135
- but `application.init` is called with `waitForGenesisBlock: false` and also `bus` module is overwiritten - so we don't (and cannot) wait for genesis block to be applied, so we end with `activeDelegates` that is `[ 'c76a0e680e83f47cf07c0f46b410f3b97e424171057a0f8f0f420c613da2f7b5' ]` (notice, there is only 1 delegate)
- and then we got `Expected generator: undefined Received generator: 2b6f49383af36fd9f1a72d5d2708c8c354add89aaea7edc702c420e2d5fdf22e` because it was not possible to calculate `delegateId`

If we wait for genesis block - we finally get full 101 delegates for list calculation, but still end with error `Expected generator: 948b8b509579306694c00833ec1c0f81e964487db2206ddb1517bfeca2b0dc1b Received generator: 2b6f49383af36fd9f1a72d5d2708c8c354add89aaea7edc702c420e2d5fdf22e`
So why it fails now?
- Because before rounds rewrite revert delegates list was generated by database using data from database, so when in database we had only genesis block - round was `1`, so seed for list was `1`
- Now we pass block height to generate list, height is `489`, so round is `5` and seed for generating list is `5`
- If we replace `self.generateDelegateList(block.height` with `self.generateDelegateList(2` in https://github.com/LiskHQ/lisk/blob/175cdc9755d06459a9f734acd9addfb27fe5147d/modules/delegates.js#L135 - it pass, which confirms my theory

Also:
- It's "not recommended" to insert block with random height just after genesis block (there is no check at database level so it's possible to do that).
- application.init is not for unit tests and was not intended to be used together with modulesLoader and custom scopes - we cannot be sure how it will affect app behavior.
