### ISSUE TITLE
Refactor accounts db repository

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1442]
Parent: #1375

This is a quick follow-up on [PR-1312](https://github.com/LiskHQ/lisk/pull/1312) that was just merged, primarily to address what's apparent:

* Use of external SQL
* Use of proper database methods
* etc

**Comment by nazarhussain** [comment]
@vitaly-t accounts repo already using external SQL files. I had moved all `Queries` object sql to seperate files. Not remember, but there can be one raw sql used in a repo method.

**Comment by vitaly-t** [comment]
accounts repo already using external SQL files

...ah, you'd think it does... :smile: 😜 Not for the SQL that's inside the `ColumnSet` objects :wink:

**Comment by nazarhussain** [comment]
Yes for ColumnSet its not... But since all our sql is dynamically generated, fields, conditions, sorting, so there is no way we can came up with a static SQL file covering every possible use case. 

We need to make some decisions, does we need dynamic selections of fields, and which attributes we should use for filters, but that can only be done with sound knowledge of each application module. So don't rush to refactor that part of the code.

**Comment by vitaly-t** [comment]
@nazarhussain Could you, please, get to me on the questions I asked you earlier in Slack?

Or, I can re-post them here...

* Is any of the `ColumnSet` objects that you create used for a non-multi-row operation? (like a regular, single-row operation)?
* About this line: https://github.com/LiskHQ/lisk/blob/1.0.0/db/repos/accounts.js#L81, Why do you first cast the result as `::int` in the query, and then re-cast it as `::bigint` through the `ColumnSet`?

**Comment by nazarhussain** [comment]
1. I am not sure what you mean by non-multi-row operation. But if you are talking about updating single row or insert single row, yes we use this columnset. 
2. For second, that's sure a typo, used to cast it into `bigint` but left `int` into query.

**Comment by vitaly-t** [comment]
Closed by [PR-1443](https://github.com/LiskHQ/lisk/pull/1443).
