### ISSUE TITLE
Integration tests pass when they have actually failed

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1444]
### Expected behavior

Integration tests should only "pass" when there all tests are actually successful (yes, really!).

### Actual behavior

Integration tests are "passing" when actually there are some test failures (yes, really not good!)

Example builds where failures are occurring on `1.0.0`:

https://jenkins.lisk.io/job/lisk-core-integration/job/1.0.0/34/console
https://jenkins.lisk.io/job/lisk-core-integration/job/1.0.0/35/console
https://jenkins.lisk.io/job/lisk-core-integration/job/1.0.0/36/console

### Steps to reproduce

Run our integration tests on Jenkins.

### Which version(s) does this affect? (Environment, OS, etc...)

`1.0.0`

**Comment by nazarhussain** [comment]
@karmacoma I did my research on this issue and found that its not related to our code base. Its the issue with the jenkins.

There are two stages defined in Jenkins file. 

https://github.com/LiskHQ/lisk/blob/6cdfef14ebc7afaeb5ae68efcf141e75c7ef2633/Jenkinsfile.integration#L56

https://github.com/LiskHQ/lisk/blob/6cdfef14ebc7afaeb5ae68efcf141e75c7ef2633/Jenkinsfile.integration#L71-L75

The first stage actually run the tests and when failed it properly reported as failed on jenkins. 

```
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
Warning: Task "exec:mocha:untagged:integration" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

But somehow Jenkins moved to second stage which is cleanup stage, and it cleanup successfully (kill pm2 process). Since that cleanup is successful, it consider the build is successful.  I had explained it in detail to @Nazgolze as well.
