### ISSUE TITLE
Mocha no pending and skipped tests

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1497]
Child of #1485
### Expected behavior
Pending test should ensure the eslint rule `/* eslint-disable mocha/no-pending-tests */` is disabled 

### Actual behavior
The following pattern is considered error
```
it("foo");
specify("foo");
test("foo");
```
### Steps to reproduce
Turn on `"mocha/no-pending-tests": "off"` and `"mocha/no-skipped-tests": "off"` run `npm run lint`

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by willclarktech** [comment]
I disagree with the expected behavior here. Where we deliberately have pending tests, we should be disabling the rule temporarily for the relevant code scope. Adding empty functions means we're unable to detect where these pending tests are.

**Comment by ManuGowda** [comment]
I agree that for now we are not going to change the skeleton to have empty function, we can specifically disable the eslint rule for now, maybe going forward whenever we have any empty skeleton test we can have the empty function. whats your take on this?

**Comment by willclarktech** [comment]
> maybe going forward whenever we have any empty skeleton test we can have the empty function

100% not. The point of the rule is so that you don't forget to write tests. In cases where you're deliberately delaying writing the tests until later (e.g. when writing test skeletons), you should turn the rule off for the relevant scope, so you can easily see where the rule has been turned off. If you add empty functions to skeleton tests you're effectively setting up false positives for yourself, with no way of automatically detecting which tests are yet to be written.

**Comment by ManuGowda** [comment]
If we turn off the rule then there is no indication externally that how many pending tests we have, so my opinion on this is we should have `it.skip('test');` and then we have the count of `pending` tests otherwise we have to go into specific files to know how many pending tests are available.
