### ISSUE TITLE
Different datatype for round number among different tables

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1647]
### Expected behavior
`round` number among different database tables should have same data type 

### Actual behavior
- In table `mem_round` the column `round` have `BIGINT` datatype
- In table `rounds_rewards` the column `round` have `INT` datatype

That cause to manipulate `round` number differently in the code when fetched from different tables. Also that may cause problems when we have larger round numbers. 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.0.0`

**Comment by vitaly-t** [comment]
> That cause to manipulate round number differently in the code when fetched from different tables

Only if the numbers can go beyond 53-bit. Otherwise, they can be all treated the same.

If numbers can go beyond 32-bit, they all definitely should be 64-bit in the database, but the code doesn't need to account for it, if numbers stay within 53 bits.

Once numbers are deemed to breach 53-bits, then it makes sense introducing one of those BigNumber modules to handle all the number manipulations.

**Comment by 4miners** [comment]
We will go with `INT` type for `round`, max value for it is `2147483647` - so will be enough.
