### ISSUE TITLE
Genesis Block applied every time when "forging.force = false"

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1889]
### Expected behavior
Genesis Block is being applied only when the blocks table is empty.
### Actual behavior
Genesis Block is being applied every time when forging.force flag is set to false in config.json.
### Steps to reproduce
Restart Node with forging.force = false flag to see Genesis Block being applied every time.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
This scenario have nothing to do with `forging.force` flag. Applying genesis block again (and the rebuild blockchain) is caused by checks in loader (probably `blockId`), should not happen anymore after solving https://github.com/LiskHQ/lisk/issues/1896. If it will happen again - please reopen this issue.
