### ISSUE TITLE
API peers response total count and count of peer in list doesn't match

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2020]
### Expected behavior
API peers endpoint should always return all the peers as mentioned in the `total` count in `meta`
### Actual behavior
API peers return inconsistent response against the `total` count of peers.

### Steps to reproduce
1. Make a GET API call to endpoint `http://188.166.111.69:4000/api/peers?state=2&limit=100&offset=0`
2. Observer the meta `total` value in the response, it will be around 150 to 200(depending on the number of connected peers at that point in time
3) Continue getting the response from offset 100 to next 100 `http://188.166.111.69:4000/api/peers?state=2&limit=100&offset=100`
4) The response will have less than expected peers.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by Mastermaulik** [comment]
Is the IP 188.166.111.69 only accessible in Lisk Office? Because I am not able to connect to this IP.

Also, I am not able to reproduce this issue on my Lisk node.
Here are the few request-response that I am getting.

Request: http://localhost:8000/api/peers?state=1&limit=100&offset=2
Response: "meta":{"offset":2,"limit":100,"total":10}
Also the response returns 8 peers

Request: http://localhost:8000/api/peers?state=1&limit=100&offset=0
Response: "meta":{"offset":2,"limit":100,"total":10}
The response returns 10 peers
