### ISSUE TITLE
Update PostgreSQL to version 10

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2147]
PostgreSQL used by Lisk Core Built version can be updated to version 10 due to obtain the better performance and increase security.

Before that, all of the queries need to be tested if working.

**Comment by 4miners** [comment]
- checked changelog between 9.6 and 10
- checked application, everything works fine

**Comment by MaciejBaj** [comment]
Corresponding issue on lisk-build - https://github.com/LiskHQ/lisk-build/issues/295

**Comment by diego-G** [comment]
Are we taking into account https://github.com/vitaly-t/pg-promise and https://github.com/vitaly-t/pg-monitor ? Please, @vitaly-t could you give us a hand regarding compatibility?

**Comment by diego-G** [comment]
@4miners are we accepting any minor change and bug fixes from Postgres? i.e. `1.X.X`. Please, @fchavant bear in mind for https://github.com/LiskHQ/lisk-docker/pull/98/files

**Comment by vitaly-t** [comment]
I have been using PostgreSQL 10.x exclusively, since its inception in early 2017.

There are no known issues with it, safe to upgrade for you guys.

On another note, I have been battling with the underlying [node-postgres] driver to make them add [support for multi-host configuration](https://github.com/brianc/node-postgres/issues/1470), even wrote my own generic [connection-string] for it, but no visible progress there.

[node-postgres]:https://github.com/brianc/node-postgres
[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by 4miners** [comment]
@diego-G Yes, according to PostgreSQL's versioning policy - `All users should upgrade to the most recent minor release as soon as possible.`
