### ISSUE TITLE
DPOS Rank Calculation (Feature Request)

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#215]
The DPOS system should be changed so that it takes into account the users productivity not just the vote weight, thus ensuring even if a user has a high vote weight but has bad productivity they get pushed down for a while. This enhances the security of the network and makes the overall appeal of the network greater for those who do not like DPOS. Something like w (weight) -= (x (missed blocks) / y (time) < a (100 network average) )

**Comment by ByronAP** [comment]
w -= x/y / a

**Comment by ByronAP** [comment]
maybe where t = total weight of top 101

e/(t/101) -= (x/y) / a

**Comment by fix** [comment]
Well this is not DPoS you are proposing, but something new.

It is not easy to see the risks of this approach. The point of PoS (and thus DPoS) is based on the assumption that the people that are the most involved (as per "money invested") are more "willing" to behave correctly to secure the network (otherwise they would lose their money because the token has no value). From this statement, if we want to improve DPoS, we need to find a way to "push" stakeholders to vote "well", and we preserve the DPoS main strength.

Now we are assuming that stakeholders are not behaving perfectly (we would say not optimising their utility in macro economy) ie they are not voting for the best delegates and thus not behaving in their own interest. Human beings...

Ideally, anybody with a Lisk account SHOULD regularly check the active delegates and act accordingly (ie change their votes)

Now back to your idea: it is weakening the responsibility of stakeholders. The very danger of your idea is that we will move slowly to PoD (proof of delegate, securing by the most active) which is basically NOT secured (i would call it heaven of hackers...). Why? because if we send the message to stakeholders that the network is going to adapt itself, the situation will be worsening... and then your "a" parameter will be adjusted and so on...

In DPoS, active delegates that are not forging are already "punished" (no reward). Maybe we could punish more (no fees sharing), but we can't prevent them from securing the network without the active consent of stakeholders.

Bottom-line: your idea is good to solve the problem now but will raise some bigger issues later. I believe that the security of the network is not hammered at all by a low productivity of a few forging delegate. 

Personally i would not touched the DPoS.

**Comment by ByronAP** [comment]
I think you misunderstand how this would work a bit. The node that is not producing blocks simply gets a hit to their weight and there position based on the number of missed blocks relative to the total average weight of the top 100 nodes. So If you are at 50 and miss enough blocks that your weight goes below the last forging node you would need to wait until your weight comes back up. You could even add a time variable say last 24 hours into the mix so that the most time they would be dropped is a day. 

Yes this is not strict DPOS it is better. It ensures productivity not just reward. There is no security issues with this and would not be "heaven for hackers". The worst case would be some bad actor blasts a node causing it to not forge and it's weight drops and gets kicked back for a day while another node takes over for a day.

Your post actually reinforces why this is needed. As it stands right now I can very easily stop all block production on all nodes. If this scheme is used that becomes very hard to do since other nodes would temporarily hold the network up.

**Comment by fix** [comment]
If there is no delegates are forging, while stopped, the network is still secured (your lisk won't escape from your account).

However if all delegates are unavailable and the other nodes are forging for them, i can tell you the network is NOT secured at all. It would be a dramatic incentive for hackers...

Just decorrelate security (linked to a consensus) from technical viability. This is something completely different. You could have a network stopped for months and still secure, while perfectly running and completely insecure.

We can do whatever but we can't break the DPoS consensus ie promoting a non consented delegate or preventing a consented delegate from forging.

That said we can view it differently: Is choosing 101 best producers out of the 121 most voted (slightly different but close to your solution) breaking DPoS? I think so. Because 121 will become soon 131, 201 and so on. The strength of the DPoS consensus is based on the responsibility awareness of the voters. If we develop technical solutions to "compensate" the lack of responsibility the consensus is weaker.

This discussion is similar to the soft/hard fork issue on ethereum right now. While being a good technical solution to help some ethereum stakeholders recover their money, it could harm very badly the PoW consensus.

**Comment by ByronAP** [comment]
DPOS does  other dictate how many delegates there are only that they be elected. This would not deviate from that as the standby nodes have been voted to there position.

The network as a whole stands to gain from this. The only people who would not want this system are people whome act only in regard to profit and Self gain as it could potentially mean they would be penalized even more for missed blocks. You also ignore the fact that it is in the interest of the network to continue moving even if I wipe all of the active delegates off.

This solution is in the best interest of the network as a whole and increases it's durability. Which actually is a selling point. I understand you may only care about your investment but for the project to move forward in the long term it is better to have a system that presents its own solution to problems, enhances the customers flexibility, and provides the utmost in durability and speed.

**Comment by ByronAP** [comment]
BTW there is no human choosing anything nor is the power of voting consensus being diminished.

Quite the opposite actually, as your vote no matter where you place it would be even more important.

**Comment by fix** [comment]
@MaxKK @karmacoma I think this issue is out of the scope of the core dev. There should be a place somewhere to make this discussion ongoing.
