### ISSUE TITLE
SSL breaks Websocket connection

### ISSUE THREAD

**Issue by Slamper** [LiskHQ/lisk#2154]
### Expected behavior
With SSL enabled incoming websocket connections should work.

### Actual behavior
With SSL enabled incoming Websocket connections fail.

Since no incoming Websocket connections are being established the broadhash consensus can only be established every 30 seconds (when `peer.rpc.status` is called) as no `updateMyself` broadcasts can reach the node. See #2083

The problems are the following:

SocketCluster enables the secure flag when https is enabled. Therefore incoming connections need to use `wss `as protocol. Currently the peer headers don't contain a flag signaling whether the node has secure websocket connections enabled which is why other peers can't know whether they have to connect via `ws` or `wss` => The connection fails with secure peers.

Peer connections are established using the IP address and not hostnames. Therefore the certificate validation fails when a secure WebSocket connection is being established. If cert checking should be disabled the `rejectUnauthorized` flag would have to be set. However this would essentially make the secure connection pointless.

### Steps to reproduce

Launch a Lisk Core node with HTTPS enabled in the config.

### Proposed solution

Disable HTTPs for WebSocket connections as certificate validation is not really possible without hostnames/domains and implement a better encryption mechanism post-1.0.0.

Completely remove the SSL options from Lisk Core. It just adds unnecessary complexity and is not as performant as using a reverse proxy like nginx to do SSL Termination. I'd rather recommend to add a guide on how to setup the Lisk core in conjunction with nginx/etc.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0+

**Comment by Gr33nDrag0n69** [comment]
Good job filling the issue, it was pretty late yesterday when I finnaly found the root cause and fixed it on my servers. For sure it would be best to solve the problem in the core to keep that nice feature bundled but yes, in the end, nginx ssl offloading do the job perfectly (even better the lisk code)

For example, I can bring the SSL score to A+ with nginx when lisk node allow only to go up to B / B+.

If community and/or lisk hq ask for it, I can write a simple guide for the community since I have lot of experiences with nginx.

**Comment by Gr33nDrag0n69** [comment]
About the scoring (for the record), I'm using this tool: https://www.ssllabs.com/ssltest/

**Comment by Gr33nDrag0n69** [comment]
I don't think it is worth having TLS between peers.  Only calls to private endpoints (for monitoring, auto-forging switch, etc) are important to stay encrypted.

**Comment by Gr33nDrag0n69** [comment]
One last note, I didn't tested self-signed certs. I used let's encrypt certificates for all my testing (certbot, same for the last 2 years)

**Comment by Gr33nDrag0n69** [comment]
Rethinking about it, I can see one disadvantage of using nginx as ssl offloader. It's not that bad but could complicate the implementation a bit. It's the API whitelisting. Since using nginx in front will always relay on 127.0.0.1, using nginx "bypass" the whitelist and public settings of API in config.json. The only work around I can think in this case is that who can access port 443 must be manage by firewall. (a bit more conplicated then just configure it in config.json)

**Comment by Gr33nDrag0n69** [comment]
In simple terms, without control of who can access port 443 of the server (using firewall), nginx will unlock API calls at large even with strick whitelist policy of lisk-node.

**Comment by jondubois** [comment]
@Gr33nDrag0n69 Good point, I guess a potential workaround could be to use the `X-Forwarded-For` HTTP header from nginx to figure out the IP of the end-client.

**Comment by Gr33nDrag0n69** [comment]
@jondubois I guess that would solve the but I never tested it with lisk.
@nazarhussain I agree mid-term, one solution should be pushed for and the other ditched, but short term with new version of lisk, the TLS Proxy would be a great workaround to current issue with bundled TLS support.

**Comment by Gr33nDrag0n69** [comment]
I still don't see any advantage to encrypt communication between nodes.

**Comment by Slamper** [comment]
@Gr33nDrag0n69 The forward HTTP Header works if you enable trust_proxy in the config.

**Comment by 4miners** [comment]
I cannot recommend `trustProxy`, as it allows to use `X-Forwarded-*` from any source IP. Implementation should be changed to allow limiting that to specific IP(s) only.

**Comment by sgdias** [comment]
I recommend keep the SSL communication between peers and make mandatory using FQDNs at config.json so there are no certificate issues, in order to avoid the need of a DNS, the map of IPs and FQDNs can be configured at hosts file.

**Comment by nazarhussain** [comment]
Opening the issue for `1.0.0-rc.2`
