### ISSUE TITLE
Low performance for transactions endpoint with sort param

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk#2201]
### Expected behavior
I expect the `/api/transactions?sort=timestamp:desc&limit=20` request to not take too long.

### Actual behavior
Can take more than 10 seconds depending of the db size

### Steps to reproduce
Request `/api/transactions?sort=timestamp:desc&limit=20`

### Which version(s) does this affect? (Environment, OS, etc...)
1.0

**Comment by lsilvs** [comment]
After a quick analise I've noticed that the low permormance was introduced in this PR https://github.com/LiskHQ/lisk/pull/1971

Adding a second column to the `ORDER BY` statement makes the query very slow. Using `ORDER BY timestamp` alone or `ORDER BY rowId` alone is fine but the combination of both is very expensive.

**Comment by 4miners** [comment]
We need to add 2 indexes for each field we're using for soring:
- `timestamp`
- `amount`
- `fee`
- `type`

It's because multicolumn index is not used when sorting `DESC`, for example:
```
CREATE INDEX trs_timestamp_row_id_asc ON trs (timestamp, "rowId" ASC);
```
`t_timestamp ASC, "t_rowId" ASC LIMIT 100 OFFSET 0` - 3.998 ms
`t_timestamp DESC, "t_rowId" ASC LIMIT 100 OFFSET 0` - 19058.764 ms

When we add both indexes:
```
CREATE INDEX trs_timestamp_asc_row_id_asc ON trs (timestamp ASC, "rowId" ASC);
CREATE INDEX trs_timestamp_desc_row_id_asc ON trs (timestamp DESC, "rowId" ASC);
```
Then actual queries utilize them:
`t_timestamp ASC, "t_rowId" ASC LIMIT 100 OFFSET 0` - 1.358 ms
`t_timestamp DESC, "t_rowId" ASC LIMIT 100 OFFSET 0` - 1.706 ms

Also we can remove indexes on `timestamp` and `type`, as new indexes covers them and performance is the same.

Storage use for added indexes:
`timestamp` - 2 x 41 MB
`amount` - 2 x 58 MB
` fee` - 2 x 58 MB
`type` - 2 x 41 MB
