### ISSUE TITLE
RPC status call gives wrong height when syncing

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#2261]
### Expected behavior

The RPC status call returns the same height as the HTTP during sync

### Actual behavior

The RPC status call returns a fixed height and broadhash for a very ling time, even if the node's height increases during sync.

In this example, I called the RPC status every 2 seconds on my node between 20:12:01 and 20:36:40 UTC. The returned status increases only a handful of times and I get the same height for a very long period of time

| height | number of status responses |
| ----| ----|
|  5030757 | 57 |
| 5038050 | 149 |
| 5039766 | 51 |
| 5041515 | 405 |
| 5044650 | 78 |

* [Series of status responses](https://gist.github.com/webmaster128/bbf730f669fea48d4411d612c494d290)
* [Logs of the syncing node](https://gist.github.com/webmaster128/9e5aa466be0cbbe6459f952355c98bdf)

### Steps to reproduce

Repeatedly run the RPC status call on a given node that is syncing

### Which version(s) does this affect? (Environment, OS, etc...)

Testnet, 1.0.0-rc.1

**Comment by MaciejBaj** [comment]
HTTP GET `api/node/status` response returns the height from modules.blocks.lastBlock.get().height - the height is always top.

RPC status returns the height out of Peer headers stored in System module. During the sync process headers are not updated after every block.

Headers will be updated only when blocks.processBlocks will be called with broadcast = true, which happens when:
1. Block is being applied after receiving through broadcast,
2. Block is being generated after successful forging.

Headers are also updated directly after the whole sync process finished -
https://github.com/LiskHQ/lisk/blob/1.0.0-rc.2/modules/loader.js#L940.

It will happen un-deterministically after node encounters an error during sync 5 times. That's why your version gathered through rpc.status was updated on particular cliffs - only when your sync loop stopped.

I wouldn't consider the current behaviour as wrong - during sync peer cannot be consider as a valid Peer to sync with for others. There is no point to broadcast headers during sync loop multiple times each second. RPC should provide the valuable messages for P2P connections purposes only. HTTP public API should be consider as a source of information for a user.
Howewer, we know that the sync process overall can be improved and we are keeping it in mind while preparing the future improvements.

**Comment by webmaster128** [comment]
Thanks for the elaborate reply. I am happy that this behavior is not the result of a bug but expected.

**Comment by nazarhussain** [comment]
@MaciejBaj I believe during sync: 

1. We should keep updating own headers after every bock 
2. So `rpc.status` can have valid height, and let on other peer to decide either sync from this peer or not
3. We should broadcast headers after sync process finished

**Comment by nazarhussain** [comment]
@MaciejBaj Yes that's exactly I suggest we should do. System itself would have latest information and yeah sure to broadcast that information it can wait for certain event in the system e.g. finish syncing.

**Comment by yatki** [comment]
closed by #2313
