### ISSUE TITLE
Rename test suites

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2273]
### Expected behavior
Rename test suites: 
- `integration` to `network`
- `system` to `integration`

### Actual behavior
The current test suite directories naming doesn't reflect its functionalities.

### Which version(s) does this affect? (Environment, OS, etc...)
`>= 1.0.0`

**Comment by ManuGowda** [comment]
@MaciejBaj @diego-G before I start working on this issue, just want to clarify that I am going to rename `integration` to `network` and `system` to `integration`, after the changes the folder structure would look like
```
  test\
       common\
       data\
       fixtures\
       functional\
       integration\
       network\
```

The functional system test will be moved out into the `integration folder` and the current `integration` folder will be renamed to `network`. Let me know if there is any concern before I start workign on this, so that we can avoid duplicate work later, Thanks.

**Comment by diego-G** [comment]
All is gut from my side. Remember we have unit test suite as well because you are not mentioning it. 
Introducing network as a whole test suite force us to change `integration network scenario` to another name avoiding redundancy https://github.com/LiskHQ/lisk/tree/development/test/integration/scenarios/network
