### ISSUE TITLE
Wait for consensus to be achieved in Peers Network tests

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2332]
### Expected behavior
Make the forging test strict, relying on waiting for a block only after the consensus has been achieved.
### Actual behaviour
Right now the expectation is to wait for 30 sec timeout:
> // Expect some blocks to be forged after 30 seconds
### Which version(s) does this affect? (Environment, OS, etc...)
`>1.0.0`

**Comment by jondubois** [comment]
This issue is taking much longer than anticipated because our current test suite is brittle when it comes to checking when nodes are fully synced. The best way to do this reliably would be to check using the node's API (either HTTP or WS).

Some problems with the current approach:

- We rely on logs to determine the node's synched status; pm2 keeps the same log between node restarts so parsing them is not always reliable; checking log timestamps would be overcomplicating things.
- The utility logic we use to launch nodes is located in two places (in `setup/network.js` and `scenarios/common.js`) - This makes it difficult to coordinate network behaviours.
- `scenarios/common.js` does not have have access to the node's pm2Json objects - This makes it difficult to interact with the nodes via API (e.g. to figure out which node corresponds to which pm2 nodeName).
