### ISSUE TITLE
Count of unconfirmed transactions in transaction pool

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#2349]
### Expected behavior
api/node/transactions/unconfirmed
Should return real count of transactions in transaction pool

### Actual behavior
It returns count of current transactions returned

### Steps to reproduce
GET api/node/transactions/unconfirmed

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.1

**Comment by SargeKhan** [comment]
@karek314, what do you mean by "current transactions"? The endpoint currently returns the transactions that are applied to the unconfirmed state in the transaction pool.

**Comment by karek314** [comment]
But does it return all unconfirmed transactions count from pool, or just count of transaction in one specified paging response ?

**Comment by karek314** [comment]
I just sent over 1,000 transactions and it appears that no matter how many transaction I send unconfirmed count is never greater than 25. 

Neither in `api/node/transactions/unconfirmed` nor in `api/node/status`

api/node/status
`{"meta":{},"data":{"broadhash":"486f11be6d252f0dbbf1b4fbe472105e4d20343cd9b18d6188a92035a1d7e857","consensus":94,"height":6904407,"loaded":true,"networkHeight":6904407,"syncing":false,"transactions":{"confirmed":1977605,"unconfirmed":25,"unprocessed":576,"unsigned":0,"total":1978084}},"links":{}}`

So I presume that unconfirmed is not really unconfirmed transaction in pool, but this is set of transactions ready to be included in block after signature verification, while unprocessed is actually what entered transaction pool, is that correct?

**Comment by SargeKhan** [comment]
Transactions sent to a node before they are saved in a block can be in three states:

- Unconfirmed transactions
- Unprocessed transactions
- Unsigned transactions

**Unconfirmed transactions** are the transactions which are applied to the unconfirmed state of the accounts. There can only 25 transactions in unconfirmed state (at max) because applying transactions to unconfirmed state is a compute intensive task, and unconfirmed queue max size is set to 25. 

**Unprocessed transactions** are the transactions which a node has received but has not applied to the unconfirmed state of the account.

**Unsigned transactions** are the transactions which are awaiting signatures.

For receiving unprocessed transactions refer to the [documentation here.](https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.30#/Node/getPooledTransactions)

**Comment by karek314** [comment]
Thanks! Everything is clear now.
