### ISSUE TITLE
Lisk Core 1.0.1 not synching

### ISSUE THREAD

**Issue by got3nks** [LiskHQ/lisk#2355]
After upgrading to v1.0.1 our node is not synching.

`Discovering new peers failed - BadConnectionError: Event 'rpc-request' was aborted due to a bad connection`

How do we fix this?

**Comment by got3nks** [comment]
Yes it works

```
lisk@server:~/lisk-main$ curl public.lisknode.net:8000/api/node/status
{"meta":{},"data":{"broadhash":"471f63422d319ec1741669f16a2a7add3dd753a293d0bc33569a04a4dec89af4","consensus":100,"height":6917190,"loaded":true,"networkHeight":6917190,"syncing":false,"transactions":{"confirmed":1981200,"unconfirmed":0,"unprocessed":0,"unsigned":1,"total":1981201}},"links":{}}
```

But our Node is still unable to sync:

`[ERR] 2018-08-31 08:01:52 | Discovering new peers failed - BadConnectionError: Event 'rpc-request' was aborted due to a bad connection`

**Comment by 4miners** [comment]
@got3nks From the API response you posted looks like node is already in sync with the network. The error `Discovering new peers failed` can happen when peers discovery operation (finding new peers to connect with) fails because the bad peer is selected, this operation is performed every half a minute - so finally node should be able to complete it, but even if not - it's not really required for node to work correctly.

**Comment by got3nks** [comment]
@4miners The API response is from the node hosted at public.lisknode.net, as suggested by @MaciejBaj . Our node is not synching.

**Comment by 4miners** [comment]
Can you provide any details about your server and internet connection? Like for example which data center or country, server spec, firewalls, etc.
Also, try to edit `config.json` and put my nodes as only seeds:
```
		"list": [
		  {
			"ip": "192.154.224.141",
			"wsPort": 8001
		  },
		  {
			"ip": "192.154.224.137",
			"wsPort": 7001
		  }
		],
```

**Comment by got3nks** [comment]
Disabling the firewall worked. What are the ports I should whitelist?
