### ISSUE TITLE
Transaction verify unit test failing due to invalid signature

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2361]
### Expected behavior
The logic transaction verify should return an error when transaction amount is invalid

### Actual behavior
The logic transaction verify unit test is failing as the transaction signature is invalid due `amount`
and `fee` is changed to Bignum and the signature is no more valid.

### Steps to reproduce
Run Unit test `test/unit/logic/transaction.js`
### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0

**Comment by diego-G** [comment]
@ManuGowda @4miners the case you fixed here, it's captured in two different places never arriving the database. Z-schema throws an error and the transaction logic too. What it means, it's impossible to happen. Actually I miss a functional test in the PR to actually prove the scenario.

We've got back to this issue because the configuration added to our custom BigNum, https://github.com/LiskHQ/lisk/blob/39c2848cb4199479624264539d97ee6696a25117/helpers/bignum.js#L33 It is forcing duplication of code or the need of symlinks between different modules. 

The current question is if we really need that configuration. Please, could you remind us the scenarios?

FYI @limiaspasdaniel

**Comment by ManuGowda** [comment]
@diego-G where do we have the `duplication of code`? Yes, we need this bignum configuration to ensure it never returns exponential format result which can result in the signature difference.

**Comment by 4miners** [comment]
We can remove this configuration, but then we should use `.toFixed()` when converting BigNumber instances to strings, instead of `.toString()`.
