### ISSUE TITLE
Update P2P layer connection logic so it can work with 1.0.0-rc.* releases

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2389]
### Expected behavior
After releasing `1.1.0-rc.0` it should be able to connect with all ` 1.0.0-rc.*` release and vice versa. 

### Actual behavior
Due to changes introduced in https://github.com/LiskHQ/lisk/pull/2181 specially the commit https://github.com/LiskHQ/lisk/commit/b3f84731dffd8b94f61bc92ec097f3612754312d we moved from `semver.satisfies` to `semver.gte`, so any node running `semver.satisfies` can't accept connections from latest rc release. 

### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0-rc.0

**Comment by MaciejBaj** [comment]
Because of the mismatch of behaviours between `semver.gte` and `semver.satisfies` for the next release candidates:
```
semver.satisfies('1.1.0-rc.0', '>=1.0.0-rc.2'); // (situation on v1.0 nodes) 
> false
semver.satisfies('1.1.0-rc.0', '1.0.0-rc.2'); // (situation on v1.1 nodes) 
> true
```
the minVersion of Testnet `1.1.0-rc.0` candidate was bumped from `1.0.0-rc.2` to `1.1.0-rc.0` (https://github.com/LiskHQ/lisk/commit/be4d8fd7a64027a73a4a958860b1cd3831a6d863). It introduces a hard-fork on Testnet but leaves the codebase free out of patching the problem existing only on Testnet. 

The problem doesn't exist on Mainnet, as the suffixes ('rc', 'beta') are not used there. There will be no hard-fork on Mainnet, and before Mainnet release the `minVersion` will be set back to `>=1.0.0` as currently.
