### ISSUE TITLE
Cont. #376 Dynamic Fee System - Free Market System

### ISSUE THREAD

**Issue by u1trafresh** [LiskHQ/lisk#2557]
The creation of a Free Market Fee System would allow users and delegates more autonomy while still being costly to produce a sustained transaction spam attack. A lower base fee would also be more fair (to lower value accounts) and allow much more inclusion to the ecosystem.

The basic idea would be this: 
-Set the base transaction fee to 100 "lisktoshi" per byte. 
-Allow delegates to accept transactions of whatever fee they wish. 
-Allow users to set their own fee -- wallets can be programmed to dynamically adjust to an appropriate fee to be included in the next block.

**Comment by whitehat** [comment]
Sound Good. Same How Ark Done It

**Comment by karek314** [comment]
Quite similar approach was already prepared by Lisk science team.

**Comment by MaciejBaj** [comment]
Hey, improving Network Economics is on our roadmap. The solution will be presented first as a Lisk Improvement Proposal (LIP, https://github.com/liskhq/lips), but the abstract of the research is available on the website (https://lisk.io/roadmap) already:

>Introduce a dynamic fee system as a free fee market where the fixed fee for all transaction types will be removed and a minimum fee will be set in the protocol. This minimum fee will be given in terms of LSK per byte used by transactions and any transactions broadcast with a fee below that value will be rejected. For each transaction, it will be up to each user to choose the fee.

I am pretty sure it covers your idea.

As now we've opened then LIPs repository, for the future please follow the guidelines (https://github.com/LiskHQ/lips/blob/master/proposals/lip-0001.md) of submitting your ideas to the protocol change through the LIPs process, instead of opening an issue on Lisk Core directly.
