### ISSUE TITLE
Pass termination signals to the child processes

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk#3185]
### Expected behavior
We should kill the child processes with the SIGNAL that main process recieves, so module developers can exit their module gracefully.
### Actual behavior
We are not passing the signals to the shutdown function and `child.kill()` methods.
https://github.com/LiskHQ/lisk/blob/0a51e7a5f76653e74a849d8ff70e5139a6f4221e/framework/src/controller/application.js#L19-L47

**Comment by nazarhussain** [comment]
This is not required because when application receives termination signals it calls out the `unload` method for each module. And `unload` method of every module is meant to gracefully cleanup every thing related to that module. 

https://github.com/LiskHQ/lisk/blob/8f7ac1ce66e16616ecd38b7880d424630508b9ae/framework/src/controller/controller.js#L280

https://github.com/LiskHQ/lisk/blob/8f7ac1ce66e16616ecd38b7880d424630508b9ae/framework/src/controller/application.js#L275

**Comment by shuse2** [comment]
I think gracefully cleaning up part is done through `unload`, but considering #3201, after `unload` shouldn't we kill the child processes when shutting down?

**Comment by shuse2** [comment]
Superseded by #3201 and #3210.
Also, it's calling `unload` as @nazarhussain described.
