### ISSUE TITLE
Add queue counts to /api/transactions/unconfirmed

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#341]
I've noticed that even when i've broadcasted roughly ~60 transactions, maximum amount returned in "count" field in` /api/transactions/unconfirmed` was limited to 25.

**Comment by jfernanz** [comment]
In what time frame were these 60 transactions sent?

**Comment by karek314** [comment]
Of course less than 10s. For sure there was more than 25 sent in less than 10s

**Comment by jfernanz** [comment]
Ok. Do this:

- Send 100+ transactions instantly
- Have the /api/transactions/unconfirmed windows open
- Log the results and attach them here

**Comment by karek314** [comment]
Will do that tomorrow.
In meantime you can check video in #339 from test.

**Comment by karmacoma** [comment]
@karek314 It is correct to say the "unconfirmed" transaction pool is limited to 25 as per block time and current block size. However, the maximum number of transactions that can be pooled on the network is much higher. This is behavior you are seeing is by design. Transaction processing and transaction broadcasts are queued and performed in stages, not immediately.

**Comment by karek314** [comment]
@karmacoma Thank you for your reply. Can you implement another field to that endpoint indicating real number of transactions awaiting to confirm ? Or design it to display all ?
Something like
`{"success":true,"transactions":[],"count":0,"allPendingCount:"0} `

**Comment by karmacoma** [comment]
@karek314 Yes, we can add this. I agree it would be helpful to know, rather than querying each individual queue: `unconfirmed`, `queued`, `multisignature`.
