### ISSUE TITLE
app.css stylesheet definitions

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#35]
Sorry, I haven't found the \public\static\css\app.css file in any repo, so I add this here.

It seems some stylesheet definitions in the app.css are something like strange. 
Examples:
- I added a checkbox to my dapp UI, but the box was not visible. I've found the reason in the belonging stylesheet: {position:absolute;left:-9999px;visibility:hidden} I had to overwrite the style locally
- My textarea has a fixed width, this breaks all layout. I had to change it to width=100%

I am not familiar with stylesheets. I doing something fundamentally wrong?

**Comment by karmacoma** [comment]
@TheGoldenEye `\public\static\css\app.css` belongs to lisk-ui. This is generated from LESS into static CSS using grunt. If we are talking about dapps development, they have their own stylesheet rules defined within the public folder of its own sub directory.

FYI, we are using https://materializecss.com/, this might explain the checkbox issue. Certain form elements need to be wrapped by other elements in order to display properly.

Note: We have the user-interface module as a separate repository. In future, please raise any frontend issues here: https://github.com/LiskHQ/lisk-ui/issues

Many thanks, your continued evaluation of the source code is highly regarded.
