### ISSUE TITLE
Failed to sweep peers

### ISSUE THREAD

**Issue by tharude** [LiskHQ/lisk#361]
Had this error in the log today and no idea what caused it. A lot of bans some hours before, but nothing specific in the logs.

    [ERR] 2016-12-19 14:09:57 | Failed to sweep peers - Error: ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification

    at Client._readError (/home/user/lisk-main/node_modules/pg-native/index.js:80:13)
    at Client._read (/home/user/lisk-main/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)

    [ERR] 2016-12-19 14:09:58 | Peers timer - No acceptable peers found

**Comment by MaciejBaj** [comment]
I wasn't able to replicate the error while upserting peers, but the problem is probably connected with missing unique constraint on 2 columns (ip, port) used for detection if peer should be updated. The problem is mentioned in http://stackoverflow.com/questions/36799104/how-to-correctly-do-upsert-in-postgres-9-5 which links to Postgres docs https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT, which says: 

> Tip: It is often preferable to use unique index inference rather than naming a constraint directly using ON CONFLICT ON CONSTRAINT constraint_name.

So we should probably add the address constraint to peers table and then in upsert query do instead of `ON CONFLICT ("ip", "port") DO UPDATE ...` use `ON CONFLICT CONSTRAINT address ...'
