### ISSUE TITLE
Reduce block propagation latency

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#374]
Courtesy of @fix:

With 10s block time, while not using PoW consensus, the scalabilty of the network is limited with block propagation time:

If on average block propagation > 5s (number is consequence of Poisson law), delegates will start to forge from a wrong parent, because they have not received the very last blocks on time. Making active delegates entering in unrecoverable fork 1.

According to a 2013 paper from Decker and Wattenhofer in Zurich, once a BTC miner produces a block on average it takes 6.5 seconds for the block to reach 50% of nodes, 40 seconds for it to reach 95% of nodes and the mean delay is 12.6 seconds.

### Mitigation

Smart routing. Decrease block propagation latencies. Strength of DPoS: we can make reasonable assumptions about who will be forging the next blocks (being sensibly the same as last round), so making sure a node propagate the node to the the peer from which it receives the previous block forge by the generator, via some simple routing tables... Simple implementation. We could also think about including some "network quality of service" to help block propagation (number of hops, delay, etc..), but needs to amend the protocol though introduce uncles in the protocol. Slightly harder but feasible and also would be a better solution. I expect issues when crossing rounds.

Link: https://blog.ethereum.org/2014/07/11/toward-a-12-second-block-time/

Another point of improvement, as suggested by Decker and Wattenhofer is to broadcast blocks as soon as the block is verified (ie. before transactions are verified and applied). Also the possibility to broadcast block header only and when verified, download the payload from the peer that broadcasted the header.

Also, as per uncle implementation, DPoS allow us to make it a lot simpler than ethereum did, with "grandfather" instead of uncle.

**Comment by 4miners** [comment]
No, that is wrong approach.
- Delegate cannot forge from wrong parent when last block is missed. Can only forge from wrong parent if have wrong last block (is on forked chain). Common cause of missing blocks now is because nodes get out of sync without reason - that should be fixed.
- All forks 1 should be recoverable, if no - there is something wrong with rollback logic.
- DPoS is not PoW - cost to forge block is nothing in comparison with cost to mine block. When slot is missed - the loss is negligible. Add "uncle" forging will increase number of blocks floating in network - so add overhead. Also "uncle" forging can be abused in various ways and we must implement complex logic to mitigate/prevent that. Not worth it imo.

**Comment by 4miners** [comment]
I was wrong on first point. That can happen when we have following conditions:
- Delegate A forged block A
- Delegate B forged block B (parent A)
- Delegate C forged block C (parent A because he not have block B)
- Delegate C got block B.

We have a fork 5 here with competiting blocks B and C (same parent, same height, different block ID), because block B is older - C is deleted from chain. That makes block C orphaned and delegate C miss his block. However nodes cannot stuck because of that condition.

Why such condition can happen?
- Delegate B node is overloaded (with transactions or other jobs) and block creation takes to much time to stay in his delegate slot
- Network latency or some issues with block propagation (forks just before that block probably also matters)
- Delegate B is malicious and hold his block on purpose and announced it one slot later

Reopened for further discussion.
