### ISSUE TITLE
Implement new, dynamic and fair, fee system

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#376]
For example:

- Base transaction fee on bytes usage
- Prioritization of transactions by fee

**Comment by dakk** [comment]
@pcdinh all transactions are stored in nodes, I think that the bytes usage is the amount of bytes of the tx stored in the node DB. Transaction size is not equal for every transaction, ie for a dapp creation the tx also have an "asset" field populated, or a multisig tx could have more than 1 signature.

**Comment by 4miners** [comment]
@karmacoma I don't agree that bytes heavier txs should be included in blocks / broadcasted first. So 1) and 2) - not give any advantages when combined. Hovewer if we make fees adjustable by users - that makes sense and even can benefit delegates. But there is no hurry because there is very less concurrent txs in network now.

**Comment by Isabello** [comment]
@4miners the transaction with more bytes would have a bigger fee associated, and get included sooner since more LSK is being paid out.

**Comment by jfernanz** [comment]
@4miners That's correct, there is no hurry at the moment. This issue was opened but at the moment it's just an idea/concept with no concrete action behind it.
