### ISSUE TITLE
Review use of sequences (db, balance)

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#538]
Review use of sequences (db, balance) and drop use of them where not needed.

See: https://github.com/LiskHQ/lisk/blob/development/helpers/sequence.js

~Belongs to: #449~

**Comment by Tschakki** [comment]
As discussed, this issue is delayed for later, after 1.0 release.

**Comment by 4miners** [comment]
Issue is still valid, sequences should be reviewed as follows:
We currently use 3 sequences (`sequence`, `dbSequence`, `balancesSequence`)
- Check if we need both `sequence` and `dbSequence`
- Check if usage is right - for example we shouldn't mix receive blocks with other API calls, as node can not receive blocks in time because of sequence is busy with other, not that important processing
- Review if we need sequences for http API calls at all
- Review if all processing of balances-related things (transactions) is performed through `balancesSequence`

**Comment by vitaly-t** [comment]
In case this is useful, there is a promise-based [sequence] method within the [spex] library that's used by `pg-promise` internally. And that library's root can be accessed via `pgp.spex`.

[spex]:https://github.com/vitaly-t/spex
[sequence]:http://vitaly-t.github.io/spex/global.html#sequence

**Comment by vitaly-t** [comment]
Quickly threw in a PR to make that `spex` module accessible: https://github.com/LiskHQ/lisk/pull/1587

**Comment by MaciejBaj** [comment]
`dbSequence` is removed - https://github.com/LiskHQ/lisk/pull/1715.
`balancesSequence` was reviewed and the usages revised - https://github.com/LiskHQ/lisk/pull/1730
