### ISSUE TITLE
Improve block propagation

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#541]
Belongs to: #449

Old Task List: 

- [x] ~~We should trust self-forged blocks and broadcast them before verification~~
- [x] ~~Every node should decide to include (or not) block on his own - so we should broadcast block immediately without verification (we can perform schema verification only)~~
- [x] ~~Decrease block size by removing empty/insignificant properties~~
- [x] Use binary format, there are some libraries that we can use https://github.com/dcodeIO/PSON, https://github.com/mongodb/js-bson

New Task List:

- Restore block properties behavior to always include all parameters

1. Remove: https://github.com/LiskHQ/lisk/blob/development/modules/blocks/verify.js#L96
2. Remove: https://github.com/LiskHQ/lisk/blob/development/modules/blocks/verify.js#L130

- Always complete block verification BEFORE broadcast, except in the case of forging a block

**Comment by Isabello** [comment]
This Issue has been reopened for the following reasons:

It is insecure to forward a block that has not been validated.
Deleting certain fields, while saving some bytes, is not secure, as it requires mutating the block multiple times
Block ID and Height should be included in every block, and not added during other steps (such as block verify)

Therefore, this is the new task list:

- [ ] Restore block properties behavior to always include all parameters
- [ ] Move blockId and Height generation into a new place to allow them to be added by the forger, rather than the recipient
- [ ] Always complete block verification BEFORE broadcast
- [ ] Refactor `onReceiveBlock` behaviors to occur during `verify`, instead of occuring at a seperate point in time.
