### ISSUE TITLE
Delegate Round based API

### ISSUE THREAD

**Issue by commeleau** [LiskHQ/lisk#57]
It could be nice to have an api that shows statistics of delegate's votes based on a specific round.

ie: 
/api/delegates/voters?publicKey=publicKey&round=roundID

**Comment by fix** [comment]
Well, imho this is likely not in the scope of a node (ie securing the blockchain). Some informations can be output if simple to create (ie simple database query). Otherwise it would unnecessarily use node power.

The blockchain is free and open to anybody. Performing statistics on blockchain should be done separately.

**Comment by fix** [comment]
I think i will close this one as won't fix, what do you think @karmacoma
