### ISSUE TITLE
Endpoint /api/blocks does not return any data for a specific querry

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#661]
The api endpoint should return according to the documentation using the `offset` and `height` parameters the blocks around a special height.

`http://testserver:7000/api/blocks?offset=30&height=35000`

In this case the response look like this:

`{"success":true,"blocks":[],"count":1}`

**Comment by 4miners** [comment]
@cezarsn That endpoint works as expected. You specified `height=35000` so it will return all blocks that are on height `35000`, `count` inform that total matches are `1` (because there will be always 1 block at certain height), and then because you specified `offset=30` it will skip that 1 block from results set - so you end with empty array.

Documentation https://docs.lisk.io/v1.1/docs/lisk-api-080-blocks tell nothing about that it should return blocks around specified height, and attached example is pretty clear.

Please close issue if you don't have further questions.

**Comment by pcdinh** [comment]
"blocks" is an empty array but "count" is 1. What does it mean? "count" is not documented
