### ISSUE TITLE
Can't send multiple transactions with the same recipientId and amount within one second

### ISSUE THREAD

**Issue by ichuan** [LiskHQ/lisk#673]
Hi!

Using the `PUT /api/transactions` API, when i'm trying to send repeated same requests, seems only the first one in a second is valid:

> 
> {"success":true,"transactionId":"1802137093118077382"}
> {"success":false,"error":"Transaction is already processed: 1802137093118077382"}
> {"success":false,"error":"Transaction is already processed: 1802137093118077382"}
> {"success":false,"error":"Transaction is already processed: 1802137093118077382"}
> {"success":false,"error":"Transaction is already processed: 1802137093118077382"}
> {"success":false,"error":"Transaction is already processed: 1802137093118077382"}
> {"success":true,"transactionId":"7979628469832278010"}
> {"success":false,"error":"Transaction is already processed: 7979628469832278010"}
> {"success":false,"error":"Transaction is already processed: 7979628469832278010"}
> {"success":false,"error":"Transaction is already processed: 7979628469832278010"}
> {"success":false,"error":"Transaction is already processed: 7979628469832278010"}

Am i doing something wrong?

**Comment by karmacoma** [comment]
@ichuan Transaction IDs are created from a SHA256 hash that is seeded from the total transaction bytes. Those transaction bytes are summed in part using the transaction timestamp, which is the number of seconds that have elapsed since genesis. Therefore sending the same transaction repeatedly can only be done with a greater than 1 second delay between them, otherwise the same hash and id will be generated for this transaction.

In your case transaction `1802137093118077382` and `7979628469832278010` have already been received and processed by the transaction pool. Subsequent sends are deemed to be the same transaction.

If you were to vary the amount, recipientId of the transaction, the ID would change as you would expect.

**Comment by ichuan** [comment]
@karmacoma Thanks for the explanation! I see. Is that intend to prevent careless repeat spending? Or why not add a nonce number before signing to generate different transaction ids?

**Comment by Isabello** [comment]
Adding a nonce and removing timestamp reliance is something we will look into in the future. However, to do so currently requires a hardfork and fundamental change to the underlying logic of transactions processing.

**Comment by ichuan** [comment]
@Isabello Understood. Thanks!
