### ISSUE TITLE
Starting with problems

### ISSUE THREAD

**Issue by qchen006** [LiskHQ/lisk#755]
When I start the program using 

`"node app.js"`

The programs hangs, the output of consoles is:

`NOTICE:  index "peers_dapp_unique" does not exist, skipping
NOTICE:  Calculating rewards for rounds, please wait...`

Can anybody help?

**Comment by Isabello** [comment]
It is not hung. Console logging is disabled by default.

On Aug 30, 2017 07:55, "qchen006" <notifications@github.com> wrote:

When I start the program using

"node app.js"

The programs hangs, the output of consoles is:

NOTICE: index "peers_dapp_unique" does not exist, skipping NOTICE:
Calculating rewards for rounds, please wait...

Can anybody help?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LiskHQ/lisk/issues/755>, or mute the thread

**Comment by qchen006** [comment]
The 8000 port and 7000 port are not up.  How can I check if I started Lisk successfully, other than checking the 8000 port? Where are the logs? @Isabello

**Comment by Isabello** [comment]
There is a logs folder in the root directory.

**Comment by andreafspeziale** [comment]
@qchen006
You can find logs under lisk-main/logs/lisk.log or lisk-test/logs/lisk.log.

For development you can also tweak it changing the level log info by changing it in the config.json

    ...
    "fileLogLevel": "info",
    "logFileName": "logs/lisk.log",
    "consoleLogLevel": "none",
    ...

**Comment by qchen006** [comment]
@andreafspeziale  thanks.
How can I start with testnet mode?

Do you suggest setup a development environment in MacOS?

**Comment by qchen006** [comment]
@andreafspeziale 
[FTL] 2017-09-03 05:50:53 | Error: FATAL:  password authentication failed for user "root"
FATAL:  password authentication failed for user "root"

When I tried to start the program using 'node app.js' , I got the error like above.

How can I solve this?

**Comment by qchen006** [comment]
@andreafspeziale  @Isabello 
When the 8000 port will be up, here I am synchronizing the transactions, will the 8000 port be up after that?

**Comment by Isabello** [comment]
You cannot run lisk as root.

Please follow the proper installation documenation.

https://docs.lisk.io/docs/core-pre-installation

**Comment by Isabello** [comment]
Closing this issue due to lack of updates and proper solution was offered.
